# Generated by Django 3.0.8 on 2020-10-14 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', related_query_name='menu', to=settings.AUTH_USER_MODEL, verbose_name='Creator of menu'),
        ),
        migrations.AddField(
            model_name='menu',
            name='dishes',
            field=models.ManyToManyField(blank=True, null=True, related_name='menus', related_query_name='menu', to='ration.Dish', verbose_name='Dishes in menu'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', related_query_name='ingredient', to='ration.Dish', verbose_name='Dish required this ingredient'),
        ),
        migrations.AddField(
            model_name='dish',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', related_query_name='dish', to=settings.AUTH_USER_MODEL, verbose_name='Creator of dish'),
        ),
    ]
